using System.Text.Json;
using System.Text.Json.Serialization;

namespace BookStackApiClient;

/// <summary>APIデータのシリアライズ型情報</summary>
[JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(JsonDocument))]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(ApiDocResult))]
[JsonSerializable(typeof(SystemInfo))]
[JsonSerializable(typeof(AttachmentItem))]
[JsonSerializable(typeof(ListAttachmentsResult))]
[JsonSerializable(typeof(ReadAttachmentResult))]
[JsonSerializable(typeof(BookItem))]
[JsonSerializable(typeof(ListBooksResult))]
[JsonSerializable(typeof(BookContentChapter))]
[JsonSerializable(typeof(BookContentPage))]
[JsonSerializable(typeof(ReadBookResult))]
[JsonSerializable(typeof(ChapterItem))]
[JsonSerializable(typeof(ListChaptersResult))]
[JsonSerializable(typeof(ReadChapterResult))]
[JsonSerializable(typeof(PageItem))]
[JsonSerializable(typeof(ListPagesResult))]
[JsonSerializable(typeof(ReadPageResult))]
[JsonSerializable(typeof(ShelfItem))]
[JsonSerializable(typeof(ListShelvesResult))]
[JsonSerializable(typeof(ReadShelfResult))]
[JsonSerializable(typeof(CommentItem))]
[JsonSerializable(typeof(CommentDetail))]
[JsonSerializable(typeof(ListCommentsResult))]
[JsonSerializable(typeof(ImageItem))]
[JsonSerializable(typeof(ListImagesResult))]
[JsonSerializable(typeof(SearchContentBook))]
[JsonSerializable(typeof(SearchContentChapter))]
[JsonSerializable(typeof(SearchContentPage))]
[JsonSerializable(typeof(SearchContentShelf))]
[JsonSerializable(typeof(SearchResult))]
[JsonSerializable(typeof(UserItem))]
[JsonSerializable(typeof(ListUsersResult))]
[JsonSerializable(typeof(RoleItem))]
[JsonSerializable(typeof(ListRolesResult))]
[JsonSerializable(typeof(ContentPermissionsItem))]
[JsonSerializable(typeof(ImportsItem))]
[JsonSerializable(typeof(ImportsItemDetails))]
[JsonSerializable(typeof(ListImportsResult))]
[JsonSerializable(typeof(RunImportsResult))]
[JsonSerializable(typeof(DeletableContentBook))]
[JsonSerializable(typeof(DeletableContentChapter))]
[JsonSerializable(typeof(DeletableContentPage))]
[JsonSerializable(typeof(DeletableContentShelf))]
[JsonSerializable(typeof(DeletableContentParentBook))]
[JsonSerializable(typeof(DeletableContentParentChapter))]
[JsonSerializable(typeof(ListRecycleBinResult))]
[JsonSerializable(typeof(RestoreRecycleItemResult))]
[JsonSerializable(typeof(ListAuditLogResult))]

[JsonSerializable(typeof(CreateLinkAttachmentArgs))]
[JsonSerializable(typeof(UpdateLinkAttachmentArgs))]
[JsonSerializable(typeof(CreateChapterArgs))]
[JsonSerializable(typeof(UpdateChapterArgs))]
[JsonSerializable(typeof(CreatePageArgs))]
[JsonSerializable(typeof(CreateMarkdownPageInBookArgs))]
[JsonSerializable(typeof(CreateMarkdownPageInChapterArgs))]
[JsonSerializable(typeof(CreateHtmlPageInBookArgs))]
[JsonSerializable(typeof(CreateHtmlPageInChapterArgs))]
[JsonSerializable(typeof(UpdatePageArgs))]
[JsonSerializable(typeof(CreateCommentArgs))]
[JsonSerializable(typeof(UpdateCommentArgs))]
[JsonSerializable(typeof(CreateUserArgs))]
[JsonSerializable(typeof(UpdateUserArgs))]
[JsonSerializable(typeof(CreateRoleArgs))]
[JsonSerializable(typeof(UpdateRoleArgs))]
[JsonSerializable(typeof(UpdateContentPermissionsArgs))]
[JsonSerializable(typeof(RunImportsArgs))]
internal partial class BookStackTypeInfo : JsonSerializerContext;